# Generated by Django 5.2.5 on 2025-09-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_featured_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='CollaborateRequest',
        ),
    ]
