# Generated by Django 5.2.5 on 2025-09-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_profile_image_alter_about_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='content',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='about',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.AlterField(
            model_name='collaboraterequest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
